# Generated by Django 4.2.5 on 2023-12-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.IntegerField(),
        ),
    ]
